[module.websocket]
# path = /usr/local/lib/%s/modules/websocket/ # default kosongkan untuk ambil default.
module = "websocket.so"

[[routes]]
endpoint = "/ping"
method = "GET"
handler = "PingHandler" # harus diawali huruf besar.

