[server]
bind = "192.168.122.1"
port = 4519
moduleLocation = "./modules"

[database]
type = "mysql"
hostname = "localhost"
port = 3306
username = "asep"
password = "dummypass"
database = "ipoint"

[schema.users]
uid = "number"
name = "string"
password = "string"

[schema.sessions]
sid = "number"
data = "text"