[server]
bind = "192.168.122.1"
port = 4519
# if this empty, will use default location ./modules
moduleLocation = ""
# if this empty, will use default location ./lib
libraryLocation = ""

[database]
hostname = "10.1.80.36"
port = 1521
username = "cpis"
password = "meong"
database = "x4500"